# CSV to Postgres ETL

This notebook is the actual data engineering workflow for our project:

1. **Extract** — read the business's raw, messy CSV.
2. **Explore** — look at what's actually wrong with it.
3. **Clean** — fix the issues we found.
4. **Split** — break the one wide CSV into the 7 normalized tables.
5. **Load** — push each table into Postgres, in the right order.
6. **Verify** — query Postgres to confirm everything landed correctly.

!pip install PyYAML

In [1]:
import pandas as pd # for data ingestion, transformation and exploration 
import yaml # for reading the configuration file with our databse credentials 
import sqlalchemy # for connecting to the database and executing SQL queries

# For visibility 
pd.set_option("display.max_columns", 30) #allows viewing all columns 
pd.set_option("display.width", 150)

##  **Extract** — read the business's raw, messy CSV.

In [2]:
raw_data_path = "../data/Unconfirmed 92574.csv"
date_columns = ["order_date", "ship_date", "expected_delivery_date", "actual_delivery_date"]

df = pd.read_csv(raw_data_path, parse_dates=date_columns)

print("Rows:", len(df))
print("Columns:", len(df.columns))
df.head()

Rows: 204861
Columns: 29

,order_id,order_date,order_status,customer_id,customer_name,email,customer_city,customer_region,customer_country,product_id,product_name,category,unit_price,order_item_id,quantity,line_total,warehouse_id,warehouse_name,warehouse_city,warehouse_region,shipment_id,carrier_id,carrier_name,service_level,ship_date,expected_delivery_date,actual_delivery_date,delivery_status,shipping_cost
0,123126,2024-07-07,Completed,2233,Robert Jones,coxsamantha@example.net,Nalerigu,North East,Ghana,233,User-friendly zero tolerance project,Electronics,680.13,313370.0,1.0,680.13,13.0,Kasoa Distribution Center,Kasoa,Central,123126.0,4.0,Meridian Shipping,Freight,2024-07-08,2024-07-13,2024-07-16,Delayed,183.03
1,494084,2025-08-25,Completed,4560,Craig Roach,mckinneyjennifer@example.net,Tarkwa,Western,Ghana,221,Cross-platform secondary attitude,Toys & Games,696.24,1257774.0,3.0,2088.72,10.0,Tarkwa Distribution Center,Tarkwa,Western,494084.0,6.0,Coastal Express,Overnight,2025-08-27,2025-09-01,2025-09-03,Delayed,82.30
2,211063,2025-06-13,Completed,946,Joshua Gonzales,jacob61@example.net,CAPE COAST,Central,Ghana,362,Focused bi-directional groupware,Home & Garden,821.12,537466.0,7.0,5747.84,1.0,Sunyani Distribution Center,Sunyani,Bono,211063.0,5.0,Pioneer Transport,Standard,2025-06-14,2025-06-15,2025-06-17,Delayed,194.75
3,192331,2024-11-29,Processing,785,Kevin Jenkins,kingdean@example.org,Akosombo,Eastern,Ghana,499,Extended client-driven framework,Furniture,44.29,489770.0,7.0,310.03,1.0,Sunyani Distribution Center,Sunyani,Bono,192331.0,4.0,Meridian Shipping,Standard,2024-11-30,2024-12-01,NaT,In Transit,202.53
4,447985,2026-02-24,Completed,2644,Brooke Pierce,audreyrogers@example.org,Sefwi Wiawso,Western North,Ghana,298,Profit-focused real-time solution,Apparel,287.52,1140622.0,9.0,2587.68,8.0,Sekondi-Takoradi Distribution Center,Sekondi-Takoradi,Western,447985.0,6.0,Coastal Express,Overnight,2026-02-24,2026-02-28,2026-03-03,Delayed,216.70

### 2. **Explore** — Find missing values, duplicates, and other data quality issues.

In [3]:
# How many duplicate rows do we have?
num_dup_rows = df.duplicated().sum()
print(f"Duplicate Rows: {num_dup_rows}")

Duplicate Rows: 412

In [4]:
missing_data_perc = (df.isna().sum().sum()/len(df)) * 100
print(f"Percentage of missing data: {missing_data_perc:.2f}%")

Percentage of missing data: 17.28%

In [7]:
# How many missing values are in each column
df.isna().sum()

order_id                      0
order_date                    0
order_status                  0
customer_id                   0
customer_name                 0
email                      2041
customer_city                 0
customer_region               0
customer_country              0
product_id                    0
product_name                  0
category                      1
unit_price                    1
order_item_id                 1
quantity                      1
line_total                    1
warehouse_id                  1
warehouse_name                1
warehouse_city                1
warehouse_region              1
shipment_id                   1
carrier_id                    1
carrier_name                  1
service_level                 1
ship_date                     1
expected_delivery_date        1
actual_delivery_date      33338
delivery_status               1
shipping_cost                 1
dtype: int64

In [5]:
df["customer_city"].drop_duplicates().head(20)

0             Nalerigu
1               Tarkwa
2           CAPE COAST
3             Akosombo
4         Sefwi Wiawso
5                Bawku
6         SEFWI WIAWSO
7                Lawra
8             AKOSOMBO
10             Damongo
11          Cape Coast
12           Koforidua
14              OBUASI
17                KETA
19               Goaso
24             Berekum
25             Sunyani
26    SEKONDI-TAKORADI
27               LAWRA
28               ACCRA
Name: customer_city, dtype: object

# 3. **Clean** — fix the issues we found.

In [6]:
# Drop Duplicate rows
rows_before = len(df)
df = df.drop_duplicates()
rows_after = len(df)

print(f"Removed {rows_before - rows_after} duplicate rows")

Removed 412 duplicate rows

In [7]:
# Strip extra whitespaces
text_columns = df.select_dtypes(include=['object', 'string']).columns.tolist()
for column in text_columns:
    df[column] = df[column].astype(str).str.strip()
    print(f"Stripped whitespaces from {column}")

print("Done!")

Stripped whitespaces from order_status
Stripped whitespaces from customer_name
Stripped whitespaces from email
Stripped whitespaces from customer_city
Stripped whitespaces from customer_region
Stripped whitespaces from customer_country
Stripped whitespaces from product_name
Stripped whitespaces from category
Stripped whitespaces from warehouse_name
Stripped whitespaces from warehouse_city
Stripped whitespaces from warehouse_region
Stripped whitespaces from carrier_name
Stripped whitespaces from service_level
Stripped whitespaces from delivery_status
Done!

In [8]:
# Standardize city name casing so "ACCRA" will look like "Accra" 
df["customer_city"] = df["customer_city"].str.title()

# to check
df["customer_city"].drop_duplicates().head(20)

0             Nalerigu
1               Tarkwa
2           Cape Coast
3             Akosombo
4         Sefwi Wiawso
5                Bawku
7                Lawra
10             Damongo
12           Koforidua
14              Obuasi
17                Keta
19               Goaso
24             Berekum
25             Sunyani
26    Sekondi-Takoradi
28               Accra
29            Ashaiman
33              Tamale
35               Ejisu
38            Kintampo
Name: customer_city, dtype: object

In [9]:
# Fill up missing values in the email column
df['email'] = df['email'].fillna("Not Given")
df['actual_delivery_date'] = df['actual_delivery_date'].fillna("pd.NaT")
df['order_item_id'] = df['order_item_id'].fillna("Not Gotten")
df['quantity'] = df['quantity'].fillna("Not Given")
df['line_total'] = df['line_total'].fillna("Not Given")
df['warehouse_id'] = df['warehouse_id'].fillna("Not Given")
df['shipment_id'] = df['shipment_id'].fillna("Not Given")
df['carrier_id'] = df['carrier_id'].fillna("Not Given")
df['ship_date'] = df['ship_date'].fillna(pd.NaT)
df['expected_delivery_date'] = df['expected_delivery_date'].fillna("Not Given")
df['shipping_cost'] = df['shipping_cost'].fillna("Not Given")


df["email"].isna().sum()
df["actual_delivery_date"].isna().sum()

np.int64(0)

In [10]:
df = df[df["warehouse_id"] != "Not Given"]

### 4. **Split** — break the one wide CSV into the 7 normalized tables.

This part builds each table by picking the relevant columns out of the `df`, then using `drop_duplicates()` so each table only keeps **one row per entity**
(e.g. one row per warehouse, not one row per warehouse per order anymore).

In [11]:
# warehouses table
warehouse_columns = ["warehouse_id", "warehouse_name", "warehouse_city", "warehouse_region"]

# drop duplicates
warehouse_table = df[warehouse_columns].drop_duplicates(subset="warehouse_id")
# Sort by warehouse id
warehouse_table = warehouse_table.sort_values("warehouse_id")

print(f"Warehouses {len(warehouse_table)} rows")
warehouse_table.head(15)

Warehouses 15 rows

   warehouse_id                        warehouse_name    warehouse_city warehouse_region
2           1.0           Sunyani Distribution Center           Sunyani             Bono
9           2.0             Yendi Distribution Center             Yendi         Northern
26          3.0           Konongo Distribution Center           Konongo          Ashanti
11          4.0      Sefwi Wiawso Distribution Center      Sefwi Wiawso    Western North
17          5.0            Tarkwa Distribution Center            Tarkwa          Western
8           6.0            Teshie Distribution Center            Teshie    Greater Accra
13          7.0        Bolgatanga Distribution Center        Bolgatanga       Upper East
4           8.0  Sekondi-Takoradi Distribution Center  Sekondi-Takoradi          Western
7           9.0      Sefwi Wiawso Distribution Center      Sefwi Wiawso    Western North
1          10.0            Tarkwa Distribution Center            Tarkwa          Western
12         11.0              Tema Distribution Center              Tema    Greater Accra
50         12.0             Lawra Distribution Center             Lawra       Upper West
0          13.0             Kasoa Distribution Center             Kasoa          Central
18         14.0                Wa Distribution Center                Wa       Upper West
16         15.0          Nalerigu Distribution Center          Nalerigu       North East

In [12]:
# carriers table
carrier_columns = ["carrier_id", "carrier_name"]
carriers_table = df[carrier_columns].drop_duplicates(subset="carrier_id")
carriers_table = carriers_table.sort_values("carrier_id")

print("carriers:", len(carriers_table), "rows")
carriers_table.head()

carriers: 8 rows

   carrier_id         carrier_name
5         1.0  SwiftHaul Logistics
18        2.0    BlueArrow Freight
6         3.0          Nexus Cargo
0         4.0    Meridian Shipping
2         5.0    Pioneer Transport

In [13]:
# products table
product_columns = ["product_id", "product_name", "category", "unit_price"]
products_table = df[product_columns].drop_duplicates(subset="product_id")
products_table = products_table.sort_values("product_id")

print(f"products: {len(products_table)} rows")
products_table.head()

products: 500 rows

     product_id                                   product_name              category  unit_price
555           1     Quality-focused explicit pricing structure       Food & Beverage      430.54
382           2                Assimilated regional projection       Food & Beverage      259.35
313           3               Expanded eco-centric application  Industrial Equipment      293.38
460           4               Object-based homogeneous project       Health & Beauty      106.91
61            5  Devolved attitude-oriented Local Area Network         Home & Garden      621.03

In [14]:
# customers table
customer_columns = ["customer_id", "customer_name", "email", "customer_city", "customer_region", "customer_country"]
customers_table = df[customer_columns].drop_duplicates(subset="customer_id")
customers_table = customers_table.sort_values("customer_id")

print(f"customers: {len(customers_table)} rows")
customers_table.head()

customers: 5000 rows

      customer_id    customer_name                      email     customer_city customer_region customer_country
4749            1     Diana Martin          ycarr@example.net           Nkawkaw         Eastern            Ghana
3250            2  Keith Rodriguez     rowebrenda@example.net           Berekum            Bono            Ghana
7801            3  Cynthia Roberts  melissagraham@example.org  Sekondi-Takoradi         Western            Ghana
8993            4     Thomas Garza          cwood@example.net             Bawku      Upper East            Ghana
1738            5      Susan Green    stephanie22@example.org          Techiman       Bono East            Ghana

In [15]:
# orders table
order_columns = ["order_id", "customer_id", "warehouse_id", "order_date", "order_status"]
orders_table = df[order_columns].drop_duplicates(subset="order_id")
orders_table = orders_table.sort_values("order_id")

print(f"orders: {len(orders_table)} rows")
orders_table.head()

orders: 173073 rows

        order_id  customer_id warehouse_id order_date order_status
7101           7         1353          5.0 2025-12-29    Completed
4796          12         1810         12.0 2025-07-14    Completed
58586         18         2570          3.0 2026-06-21    Completed
38274         21         2372          7.0 2025-07-11    Completed
141359        29          658         12.0 2025-12-11    Completed

In [16]:
# order_items table
order_item_columns = ["order_item_id", "order_id", "order_date", "product_id", "quantity", "unit_price", "line_total"]
order_items_table = df[order_item_columns].drop_duplicates(subset="order_item_id")
order_items_table = order_items_table.sort_values("order_item_id")

print(f"order_items: {len(order_items_table)} rows")
order_items_table.head()

order_items: 204406 rows

       order_item_id  order_id order_date  product_id quantity  unit_price line_total
7101            14.0         7 2025-12-29         447      2.0      791.99    1583.98
41399           15.0         7 2025-12-29          84      6.0      895.11    5370.66
66655           24.0        12 2025-07-14          69      4.0      316.52    1266.08
4796            25.0        12 2025-07-14         483      7.0      328.10     2296.7
157488          26.0        12 2025-07-14          28      9.0      475.26    4277.34

In [17]:
# shipments table
shipment_columns = ["shipment_id", "order_id", "carrier_id", "service_level", "ship_date","expected_delivery_date", "actual_delivery_date", "delivery_status", "shipping_cost"]
shipments_table = df[shipment_columns].drop_duplicates(subset="shipment_id")
shipments_table = shipments_table.sort_values("shipment_id")

print(f"shipments: {len(shipments_table)} rows")
shipments_table.head()

shipments: 173073 rows

       shipment_id  order_id carrier_id service_level  ship_date expected_delivery_date actual_delivery_date delivery_status shipping_cost
7101           7.0         7        7.0       Express 2025-12-29    2026-01-03 00:00:00  2026-01-04 00:00:00         Delayed        153.39
4796          12.0        12        1.0       Freight 2025-07-16    2025-07-17 00:00:00  2025-07-18 00:00:00         Delayed        171.25
58586         18.0        18        2.0     Overnight 2026-06-21    2026-06-28 00:00:00  2026-06-27 00:00:00       Delivered        200.95
38274         21.0        21        3.0      Standard 2025-07-13    2025-07-22 00:00:00  2025-07-22 00:00:00       Delivered         92.06
141359        29.0        29        3.0      Standard 2025-12-12    2025-12-15 00:00:00  2025-12-17 00:00:00         Delayed        180.59

### 5. **Load** — push each table into Postgres, in the right order.

**Order matters here** because of foreign key constraints: a table can
only be loaded once the tables it references already have their rows in
place.

Load order: `warehouses` → `carriers` → `products` → `customers`
(no dependencies) → `orders` (needs customers + warehouses) →
`order_items` and `shipments` (both need orders).

We use `to_sql(..., if_exists="append")`because we have already
created the empty tables (and partitions) for us; we're only inserting
rows, not creating tables from pandas.

### Database Connection Setting

In [18]:
!pip install psycopg2-binary
import psycopg2

Requirement already satisfied: psycopg2-binary in /opt/anaconda3/lib/python3.13/site-packages (2.9.12)

In [19]:
with open('config.yaml', 'r') as file:
    config = yaml.safe_load(file)

    host = config.get('host')
    user = config.get('user')
    database_name = config.get('database')
    password = config.get('password')
    port = config.get('port')

# build the URl 
db_url = sqlalchemy.URL.create(
    drivername='postgresql+psycopg2',
    username=user,
    host=host,
    database=database_name,
    password=password,
    port=port
)

# build the engine
engine = sqlalchemy.create_engine(db_url)
print(f"Connection Ready! {db_url}")

Connection Ready! postgresql+psycopg2://postgres:***@localhost:5432/sankofa-logistics-data-warehouse

In [20]:
# Load the warehouse table - to be executed once
warehouse_table.to_sql(name="warehouses", con=engine, if_exists="append",schema="logistics", index=False)

print(f"Loaded {len(warehouse_table)} to the database {database_name}")

IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "warehouses_pkey"
DETAIL:  Key (warehouse_id)=(1) already exists.

[SQL: INSERT INTO logistics.warehouses (warehouse_id, warehouse_name, warehouse_city, warehouse_region) VALUES (%(warehouse_id__0)s, %(warehouse_name__0)s, %(warehouse_city__0)s, %(warehouse_region__0)s), (%(warehouse_id__1)s, %(warehouse_name__1)s, %(ware ... 1183 characters truncated ... s), (%(warehouse_id__14)s, %(warehouse_name__14)s, %(warehouse_city__14)s, %(warehouse_region__14)s)]
[parameters: {'warehouse_id__0': 1.0, 'warehouse_name__0': 'Sunyani Distribution Center', 'warehouse_city__0': 'Sunyani', 'warehouse_region__0': 'Bono', 'warehouse_id__1': 2.0, 'warehouse_name__1': 'Yendi Distribution Center', 'warehouse_city__1': 'Yendi', 'warehouse_region__1': 'Northern', 'warehouse_id__2': 3.0, 'warehouse_name__2': 'Konongo Distribution Center', 'warehouse_city__2': 'Konongo', 'warehouse_region__2': 'Ashanti', 'warehouse_id__3': 4.0, 'warehouse_name__3': 'Sefwi Wiawso Distribution Center', 'warehouse_city__3': 'Sefwi Wiawso', 'warehouse_region__3': 'Western North', 'warehouse_id__4': 5.0, 'warehouse_name__4': 'Tarkwa Distribution Center', 'warehouse_city__4': 'Tarkwa', 'warehouse_region__4': 'Western', 'warehouse_id__5': 6.0, 'warehouse_name__5': 'Teshie Distribution Center', 'warehouse_city__5': 'Teshie', 'warehouse_region__5': 'Greater Accra', 'warehouse_id__6': 7.0, 'warehouse_name__6': 'Bolgatanga Distribution Center', 'warehouse_city__6': 'Bolgatanga', 'warehouse_region__6': 'Upper East', 'warehouse_id__7': 8.0, 'warehouse_name__7': 'Sekondi-Takoradi Distribution Center', 'warehouse_city__7': 'Sekondi-Takoradi', 'warehouse_region__7': 'Western', 'warehouse_id__8': 9.0, 'warehouse_name__8': 'Sefwi Wiawso Distribution Center', 'warehouse_city__8': 'Sefwi Wiawso', 'warehouse_region__8': 'Western North', 'warehouse_id__9': 10.0, 'warehouse_name__9': 'Tarkwa Distribution Center', 'warehouse_city__9': 'Tarkwa', 'warehouse_region__9': 'Western', 'warehouse_id__10': 11.0, 'warehouse_name__10': 'Tema Distribution Center', 'warehouse_city__10': 'Tema', 'warehouse_region__10': 'Greater Accra', 'warehouse_id__11': 12.0, 'warehouse_name__11': 'Lawra Distribution Center', 'warehouse_city__11': 'Lawra', 'warehouse_region__11': 'Upper West', 'warehouse_id__12': 13.0, 'warehouse_name__12': 'Kasoa Distribution Center', 'warehouse_city__12': 'Kasoa', 'warehouse_region__12': 'Central', 'warehouse_id__13': 14.0, 'warehouse_name__13': 'Wa Distribution Center', 'warehouse_city__13': 'Wa', 'warehouse_region__13': 'Upper West', 'warehouse_id__14': 15.0, 'warehouse_name__14': 'Nalerigu Distribution Center', 'warehouse_city__14': 'Nalerigu', 'warehouse_region__14': 'North East'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [35]:
# Load the carriers table - to be executed once
carriers_table.to_sql(name="carriers", con=engine, if_exists="append",schema="logistics", index=False)

print(f"Loaded {len(carriers_table)} carries to the database {database_name}")

Loaded 8 carries to the database sankofa-logistics-data-warehouse

In [36]:
# Load the products table - to be executed once
products_table.to_sql(name="products", con=engine, if_exists="append",schema="logistics", index=False)

print(f"Loaded {len(products_table)} products to the database {database_name}")

Loaded 500 products to the database sankofa-logistics-data-warehouse

In [37]:
# Load the customers table - to be executed once
customers_table.to_sql(name="customers", con=engine, if_exists="append",schema="logistics", index=False)

print(f"Loaded {len(customers_table)} customers to the database {database_name}")

Loaded 5000 customers to the database sankofa-logistics-data-warehouse

In [43]:
orders_table = orders_table.dropna(subset=["warehouse_id"])

In [44]:
# Load the orders table - to be executed once
orders_table.to_sql(name="orders", con=engine, if_exists="append",schema="logistics", index=False, method='multi', chunksize=5000)

print(f"Loaded {len(orders_table)} orders to the database {database_name}")

Loaded 173073 orders to the database sankofa-logistics-data-warehouse

In [28]:
# Load the order_items table - to be executed once
order_items_table.to_sql(name="order_items", con=engine, if_exists="append",schema="logistics", index=False, method='multi', chunksize=10000)

print(f"Loaded {len(order_items_table)} order_items to the database {database_name}")

Loaded 204406 order_items to the database sankofa-logistics-data-warehouse

In [25]:
for col in ["ship_date", "expected_delivery_date", "actual_delivery_date"]:
    print(col, (shipments_table[col] == "Not Gotten").sum())

ship_date 0
expected_delivery_date 0
actual_delivery_date 28158

In [ ]:
# Load the shipments table - to be executed once
shipments_table.to_sql(name="shipments", con=engine, if_exists="append",schema="logistics", index=False, method='multi', chunksize=5000)

print(f"Loaded {len(shipments_table)} shipments to the database {database_name}")

In [25]:
table_names = ["warehouses", "carriers", "products", "customers", "orders", "order_items", "shipments"]

for table_name in table_names:
    result = pd.read_sql(f"SELECT COUNT(*) AS row_count FROM logistics.{table_name}", con=engine)
    print(table_name, "->", result["row_count"].iloc[0], "rows")

warehouses -> 15 rows
carriers -> 8 rows
products -> 500 rows
customers -> 5000 rows
orders -> 173073 rows
order_items -> 204406 rows
shipments -> 0 rows